[[Snippets]]
Description = "Print the first column of the input"
Output = ""
Tag = [ "columns",]
command = "awk '{print $1}'"

[[Snippets]]
command = "ls -l"
Description = "(lll) List the contents of the current directory in long format"
Output = ""
Tag = [ "list", "directory",]
name = "lll"

[[Snippets]]
command = "echo 'Hello world'"
Description = "Display 'Hello world'"
Output = ""
Tag = [ "a-tag", "another-tag",]

